name: CI

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          tools: cs2pr
          coverage: 'none'

      - name: "Install Dependencies with Composer"
        uses: "ramsey/composer-install@v2"

      - name: "Run PHP-CS-Fixer"
        run: vendor/bin/php-cs-fixer fix -v --dry-run --format=checkstyle | cs2pr

  phpstan:
    name: "PHPStan"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          coverage: 'none'

      - name: "Install Dependencies with Composer"
        uses: "ramsey/composer-install@v2"

      - name: "Run PHPStan"
        run: vendor/bin/phpstan analyse --error-format=github

  phpunit:
    name: "PHPUnit"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          tools: phpunit:9.5
          coverage: pcov

      - name: "Install Dependencies with Composer"
        uses: "ramsey/composer-install@v2"

      - name: "Run PHPStan"
        run: php -dpcov.enabled=1 -dpcov.directory=. -dpcov.exclude="~vendor~" vendor/bin/phpunit --coverage-text
